### ISSUE TITLE
Using Domino with mouse data

### ISSUE THREAD

**Issue by mindykimgraham** [Chris-Cherry/domino#14]
I am analyzing mouse data, but I am having trouble finding a ligand-receptor database equivalent to CellPhoneDB for mice. Do you have any suggestions on how best to proceed? I am hoping someone might have already generated the mouse equivalent files for complexes.csv, genes.csv, interactions.csv, and proteins.csv.

**Comment by Chris-Cherry** [comment]
Hi Mindy. As far as I know there isn't a database that is created with mouse genes but Domino will attempt to convert human to mouse orthologues with the gene_conv option in create_domino. If your genes are in mgi format then you would supply c('HGNC', 'MGI') to convert the CellphoneDB genes from HGNC to MGI. It also supports human and mouse ensembl IDs. Best of luck.

**Comment by mindykimgraham** [comment]
Thank you for your quick reply. I am getting the following error: 
biomaRt has encountered an unexpected server error. Consider trying one of the Ensembl mirrors (for more details look at ?useEnsembl)

I suspect it is related to the error reported here: https://support.bioconductor.org/p/9143371/

What would be the best way to update create_domino: 
"MGI" to useMart("ensembl", dataset = "hsapiens_gene_ensembl", host = "https://dec2021.archive.ensembl.org/")
"HGNC" to useMart("ensembl", dataset = "hsapiens_gene_ensembl", host = "https://dec2021.archive.ensembl.org/")
