### ISSUE TITLE
Using Domino with Omnipath interactions database

### ISSUE THREAD

**Issue by bhavyaac** [Chris-Cherry/domino#15]
Hello,
Thank you for your great work on this package, it is very clearly documented and well-implemented.
I am using Domino with transcriptomic data from mouse, using gene conversion via the `gene_conv` argument of `create_domino()`, and the results are promising. However, there are very low numbers of interactions detected in my dataset, with a maximum of 12 interactions between any given pair of cell types. I encountered a similar problem when using `biomaRt`-converted genes with the CellphoneDB tool, where the tool found 5-10 times fewer interactions in mouse samples as compared to human. Since Domino also uses the CellphoneDB database of ligand-receptor interactions, it may be possible that this is common issue related to the CellphoneDB human database itself, and not the tool implementation.
I came across the following tutorial written by the creators of Omnipath, which is an extended database of ligand-receptor interactions containing the CellphoneDB database and several others: https://workflows.omnipathdb.org/ligrec-squidpy.pdf . Their example seems to show that switching from the CellphoneDB database to Omnipath in a mouse sample increased their number of detected interactions from 9 to 107, which is very encouraging.
I am wondering whether you have any advice for me to adapt Domino to use the Omnipath database of ligand-receptor interactions instead of the CellphoneDB database. Please let me know what you think. Thank you!

**Comment by Chris-Cherry** [comment]
Hi Bhavyaa,

Thank you for the kind words on our algorithm. I'm glad you've found our documentation fairly complete. You can certainly use the ominpath database or any other database, but you'll have bit of legwork getting the data in the correct format for Domino. You will need conver the data in Ominpath into the same format as Cellphonedb2 after which Domino should be able to read and use the data. For more details, see lines 50-170 of `domino/R/import_fxns.R` which contain the code Domino uses to read in the data sets. As long as you can use the code to read in the Omnipath data you should be set.

Best of luck

**Comment by bhavyaac** [comment]
Hi, thank you for the quick response! I will try this.
